
// 客户地址查询
export const columnsCTrI1 = [
    {field: "custId", label: "客户编号", width: '200', align: ''},
    {field: "custName", label: "客户名称", width: '200', align: ''},
    {field: "custType", label: "客户类型", width: '200', align: ''},
    {field: "bankSwift", label: "开户银行", width: '200', align: ''},
    {field: "bankAcct", label: "银行帐号", width: '200', align: ''},
    {field: "bankday", label: "开户日期", width: '200', align: ''},
    {field: "addr", label: "地址", width: '250', align: ''},
    {field: "zipCd", label: "邮编", width: '200', align: ''},
    {field: "phone", label: "电话号码", width: '200', align: ''},
    {field: "sex", label: "性别", width: '200', align: ''},
    {field: "birthdt", label: "出生日期", width: '200', align: ''},
    {field: "localTaxid", label: "当地纳税号", width: '200', align: ''},
    {field: "localSocialsecurityid", label: "当地", width: '200', align: ''},
    {field: "localId", label: "当地身份证号", width: '250', align: ''},
    {field: "licenceid", label: "驾照号", width: '200', align: ''},
    {field: "hkMacaoPass", label: "港澳居民来往内地通行证", width: '250', align: ''},
    {field: "workUnit", label: "工作单位", width: '200', align: ''},
    {field: "position", label: "职位", width: '200', align: ''},
    {field: "corpChar", label: "单位性质", width: '200', align: ''},
    {field: "email", label: "电子邮件", width: '250', align: ''},
    {field: "zdxSoloName", label: "指定下单人姓名", width: '200', align: ''},
    {field: "zdxSoloDoctype", label: "指定下单人证件类型", width: '250', align: ''},
    {field: "zdxSoloDocid", label: "指定下单人证件号码", width: '250', align: ''},
    {field: "zdxSoloAddr", label: "指定下单人地址", width: '200', align: ''},
    {field: "zdxSoloZipCd", label: "指定下单人邮编", width: '200', align: ''},
    {field: "fundTranpername", label: "资金调拨人姓名", width: '200', align: ''},
    {field: "fundTranperaddr", label: "资金调拨人地址", width: '200', align: ''},
    {field: "fundTranperzipCd", label: "资金调拨人邮编", width: '200', align: ''},
    {field: "statCfmname", label: "结算单确认人姓名", width: '200', align: ''},
    {field: "statCfmaddr", label: "结算单确认人地址", width: '250', align: ''},
    {field: "statCfmzipCd", label: "结算单确认人邮编", width: '200', align: ''},
    {field: "custOpenmodel", label: "客户开户模式", width: '200', align: ''},
    {field: "oaiName", label: "开户或中介机构名称", width: '250', align: ''},
    {field: "oaiFilingid", label: "开户或中介机构备案号", width: '250', align: ''},

];

// 客户交易信息查询

// 精确信息查询
export const columnsCTrI3 = [
    {field: "acctNum1", label: "精确信息查询", width: '200', align: ''},
    {field: "custId", label: "客户号", width: '200', align: ''},
    {field: "custName", label: "客户名称", width: '200', align: ''},
    {field: "custType", label: "客户类型", width: '200', align: ''},
    {field: "bankSwift", label: "开户银行", width: '250', align: ''},
    {field: "bankIacct", label: "银行帐号", width: '250', align: ''},
    {field: "bankDay", label: "开户日期", width: '200', align: ''},
    {field: "addr", label: "地址", width: '250', align: ''},
    {field: "zipCd", label: "邮编", width: '200', align: ''},
    {field: "phone", label: "电话号码", width: '200', align: ''},
    {field: "sex", label: "性别", width: '200', align: ''},
    {field: "birthdt", label: "出生日期", width: '200', align: ''},
    {field: "localTaxid", label: "当地纳税号", width: '200', align: ''},
    {field: "localSocialsecurityid", label: "当地社保id", width: '200', align: ''},
    {field: "localId", label: "当地身份证号", width: '250', align: ''},
    {field: "licenceId", label: "驾照号", width: '250', align: ''},
    {field: "hkMacaoPass", label: "港澳居民来往内地通行证", width: '250', align: ''},
    {field: "workUnit", label: "工作单位", width: '250', align: ''},
    {field: "position", label: "职位", width: '200', align: ''},
    {field: "corpChar", label: "单位性质", width: '200', align: ''},
    {field: "email", label: "电子邮件", width: '250', align: ''},
    {field: "zdxSoloName", label: "指定下单人姓名", width: '200', align: ''},
    {field: "zdxSoloDoctype", label: "指定下单人证件类型", width: '250', align: ''},
    {field: "zdxSoloDocid", label: "指定下单人证件号码", width: '250', align: ''},
    {field: "zdxoloddr", label: "指定下单人地址", width: '250', align: ''},
    {field: "zdxoloZipCd", label: "指定下单人邮编", width: '200', align: ''},
    {field: "fundTranpername", label: "资金调拨人姓名", width: '200', align: ''},
    {field: "fundSasTranperaddr", label: "资金调拨人地址", width: '250', align: ''},
    {field: "fundTranperzipCd", label: "资金调拨人邮编", width: '200', align: ''},
    {field: "statCfmname", label: "结算单确认人姓名", width: '200', align: ''},
    {field: "statCfmaddr", label: "结算单确认人地址", width: '250', align: ''},
    {field: "statCfmzipCd", label: "结算单确认人邮编", width: '200', align: ''},
    {field: "custOpenmodel", label: "客户开户模式", width: '250', align: ''},
    {field: "oaiName", label: "开户或中介机构名称", width: '250', align: ''},
    {field: "oaiFilingid", label: "开户或中介机构备案号", width: '250', align: ''},
];

// 指标选择
export const indexSelectionOptions = [
    {value: '1', label: '地址'},
    {value: '2', label: '电话'},
    {value: '3', label: '工作单位'},
    {value: '4', label: '电子邮件'},
];
// 模糊地址查询
export const columnsCTrI4 = [
    {field: "custName", label: "客户名称", width: '250', align: ''},
    {field: "custType", label: "客户类型", width: '200', align: ''},
    {field: "bankSwift", label: "开户银行", width: '200', align: ''},
    {field: "bankAcct", label: "银行帐号", width: '200', align: ''},
    {field: "bankDay", label: "开户日期", width: '200', align: ''},
    {field: "addr", label: "地址", width: '250', align: ''},
    {field: "zipCd", label: "邮编", width: '200', align: ''},
    {field: "phone", label: "电话号码", width: '200', align: ''},
    {field: "sex", label: "性别", width: '200', align: ''},
    {field: "birthdt", label: "出生日期", width: '200', align: ''},
    {field: "localTaxid", label: "客户号", width: '200', align: ''},
    {field: "localSocialsecurityid", label: "客户名称", width: '200', align: ''},
    {field: "localId", label: "客户类型", width: '200', align: ''},
    {field: "licenceId", label: "开户银行", width: '250', align: ''},
    {field: "hkMacaoPass", label: "银行帐号", width: '250', align: ''},
    {field: "workUnit", label: "开户日期", width: '200', align: ''},
    {field: "position", label: "地址", width: '250', align: ''},
    {field: "corpChar", label: "邮编", width: '200', align: ''},
    {field: "email", label: "电话号码", width: '200', align: ''},
    {field: "zdxSoloName", label: "性别", width: '200', align: ''},
    {field: "zdxSoloDoctype", label: "出生日期", width: '200', align: ''},
    {field: "zdxSoloDocid", label: "当地纳税号", width: '250', align: ''},
    {field: "zdxSoloAddr", label: "当地社保id", width: '250', align: ''},
    {field: "zdxSoloZipCd", label: "当地身份证号", width: '250', align: ''},
    {field: "fundTranpername", label: "驾照号", width: '250', align: ''},
    {field: "fundTranperaddr", label: "港澳居民来往内地通行", width: '250', align: ''},
    {field: "fundTranperzipCd", label: "工作单位", width: '250', align: ''},
    {field: "statCfmname", label: "职位", width: '200', align: ''},
    {field: "statCfmaddr", label: "单位性质", width: '200', align: ''},
    {field: "statCfmzipCd", label: "电子邮件", width: '250', align: ''},
    {field: "custOpenmodel", label: "指定下单人姓名", width: '200', align: ''},
    {field: "oaiName", label: "指定下单人证件类型", width: '200', align: ''},
];
